workflows:
  android-debug-workflow:
    name: HM-check Debug Build
    max_build_duration: 15
    environment:
      java: 17
    scripts:
      - name: Grant execute permission for gradlew
        script: |
          if [ -f ./gradlew ]; then
            chmod +x gradlew
          else
            gradle wrapper --gradle-version 8.5
            chmod +x gradlew
          fi
      - name: Build Debug APK
        script: ./gradlew assembleDebug --no-daemon
    artifacts:
      - app/build/outputs/apk/debug/*.apk
